### ISSUE TITLE
hitting enter in the input box after typing a letter throws error. 

### ISSUE THREAD

**Issue by mohitmayank** [viveksri96/refrens-frontend#1]
![Screenshot from 2021-01-19 12-36-59](https://user-images.githubusercontent.com/1619845/104999590-1cfc1500-5a53-11eb-9ba6-cf698309e856.png)

**Comment by viveksri96** [comment]
@mohitmayank Fixed 
5a158b646ad96731f37473c6085941a94a29c08a
